from __future__ import annotations

import argparse
from pathlib import Path

REQUIRED = (
    "BITCOIN_LIVE_INPUT_REFRESH_AND_V4_OPERATIONALIZATION_GOVERNANCE_V1",
    "MODULE1_INCREMENTAL_REFRESH_AUTHORIZED=TRUE",
    "MODULE1_FULL_REFRESH_AUTHORIZED=FALSE",
    "MODULE6_SYNC_AUTHORIZED=TRUE",
    "MODULE6_RESEARCH_PHASE_AUTHORIZED=FALSE",
    "LIVE_SOURCE_DATA_REFRESH_AUTHORIZED=TRUE",
    "EXISTING_MODULE1_MACRO_REFRESH_AUTHORIZED=TRUE",
    "SYNTHETIC_MACRO_EVIDENCE_ALLOWED=FALSE",
    "V4_7D_FROZEN_FAMILY_OPERATIONAL_REFIT_AUTHORIZED=TRUE",
    "V4_MODEL_SELECTION_REOPENED=FALSE",
    "V4_POST_HOLDOUT_TUNING_AUTHORIZED=FALSE",
    "V4_HYPERPARAMETER_SEARCH_AUTHORIZED=FALSE",
    "V4_FEATURE_CONTRACT_CHANGE_AUTHORIZED=FALSE",
    "V4_30D_QUALIFIED_PREDICTION_AUTHORIZED=FALSE",
    "V4_365D_QUALIFIED_PREDICTION_AUTHORIZED=FALSE",
    "LEGACY_M38_SUBSTITUTION_FOR_V4_ALLOWED=FALSE",
    "MODULE42_HISTORICAL_CONTEXT_ALLOWED=TRUE",
    "MODULE42_RERUN_AUTHORIZED=FALSE",
    "MODEL_PORTFOLIO_AS_PERSONAL_HOLDINGS_ALLOWED=FALSE",
    "FIRST_PROSPECTIVE_OBSERVATION_CAPTURE_AUTHORIZED=FALSE",
    "BTC_ETH_RECOMMENDATION_POLICY_SKILL_CERTIFIED=FALSE",
    "PRODUCTION_POLICY_CHANGE_AUTHORIZED=FALSE",
    "AUTONOMOUS_EXECUTION_AUTHORIZED=FALSE",
    "BUILD_AND_VALIDATE_BITCOIN_LIVE_REFRESH_AND_V4_OPERATIONALIZATION_RUNNER",
    "V4_7D_VOLATILITY_STATE_EXTRA_TREES",
    "NO_QUALIFIED_WINNER",
    "run_module1.py",
    "run_module6.py --phase sync",
    "--full-refresh",
    "FRED_API_KEY",
)

PROHIBITED_TRUE = (
    "MODULE1_FULL_REFRESH_AUTHORIZED=TRUE",
    "MODULE6_RESEARCH_PHASE_AUTHORIZED=TRUE",
    "SYNTHETIC_MACRO_EVIDENCE_ALLOWED=TRUE",
    "V4_MODEL_SELECTION_REOPENED=TRUE",
    "V4_POST_HOLDOUT_TUNING_AUTHORIZED=TRUE",
    "V4_HYPERPARAMETER_SEARCH_AUTHORIZED=TRUE",
    "V4_FEATURE_CONTRACT_CHANGE_AUTHORIZED=TRUE",
    "V4_30D_QUALIFIED_PREDICTION_AUTHORIZED=TRUE",
    "V4_365D_QUALIFIED_PREDICTION_AUTHORIZED=TRUE",
    "LEGACY_M38_SUBSTITUTION_FOR_V4_ALLOWED=TRUE",
    "MODULE42_RERUN_AUTHORIZED=TRUE",
    "MODEL_PORTFOLIO_AS_PERSONAL_HOLDINGS_ALLOWED=TRUE",
    "FIRST_PROSPECTIVE_OBSERVATION_CAPTURE_AUTHORIZED=TRUE",
    "BTC_ETH_RECOMMENDATION_POLICY_SKILL_CERTIFIED=TRUE",
    "PRODUCTION_POLICY_CHANGE_AUTHORIZED=TRUE",
    "AUTONOMOUS_EXECUTION_AUTHORIZED=TRUE",
)


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--governance", required=True)
    args = parser.parse_args()

    path = Path(args.governance).resolve()
    require(path.is_file(), f"Governance file missing: {path}")
    text = path.read_text(encoding="utf-8")

    for fragment in REQUIRED:
        require(fragment in text, f"Required governance fragment missing: {fragment}")

    for fragment in PROHIBITED_TRUE:
        require(fragment not in text, f"Prohibited authority unexpectedly granted: {fragment}")

    print("BITCOIN_LIVE_INPUT_REFRESH_AND_V4_OPERATIONALIZATION_GOVERNANCE_VALIDATION=PASS")
    print("MODULE1_INCREMENTAL_REFRESH_AUTHORIZED=TRUE")
    print("MODULE1_FULL_REFRESH_AUTHORIZED=FALSE")
    print("MODULE6_SYNC_AUTHORIZED=TRUE")
    print("MODULE6_RESEARCH_PHASE_AUTHORIZED=FALSE")
    print("EXISTING_MODULE1_MACRO_REFRESH_AUTHORIZED=TRUE")
    print("SYNTHETIC_MACRO_EVIDENCE_ALLOWED=FALSE")
    print("V4_7D_FROZEN_FAMILY_OPERATIONAL_REFIT_AUTHORIZED=TRUE")
    print("V4_MODEL_SELECTION_REOPENED=FALSE")
    print("V4_POST_HOLDOUT_TUNING_AUTHORIZED=FALSE")
    print("V4_HYPERPARAMETER_SEARCH_AUTHORIZED=FALSE")
    print("V4_FEATURE_CONTRACT_CHANGE_AUTHORIZED=FALSE")
    print("V4_30D_QUALIFIED_PREDICTION_AUTHORIZED=FALSE")
    print("V4_365D_QUALIFIED_PREDICTION_AUTHORIZED=FALSE")
    print("LEGACY_M38_SUBSTITUTION_FOR_V4_ALLOWED=FALSE")
    print("MODULE42_RERUN_AUTHORIZED=FALSE")
    print("MODEL_PORTFOLIO_AS_PERSONAL_HOLDINGS_ALLOWED=FALSE")
    print("FIRST_PROSPECTIVE_OBSERVATION_CAPTURE_AUTHORIZED=FALSE")
    print("BTC_ETH_RECOMMENDATION_POLICY_SKILL_CERTIFIED=FALSE")
    print("PRODUCTION_POLICY_CHANGE_AUTHORIZED=FALSE")
    print("AUTONOMOUS_EXECUTION_AUTHORIZED=FALSE")
    print("NEXT_GATE=BUILD_AND_VALIDATE_BITCOIN_LIVE_REFRESH_AND_V4_OPERATIONALIZATION_RUNNER")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
